apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "pensjon-regler-beregn"
  namespace: "pensjon-regler"
  labels:
    team: "pensjon-regler"
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 2
    max: 2
  liveness:
    path: "/index.html"
    initialDelay: 40
    timeout: 3
  readiness:
    path: "/index.html"
    initialDelay: 40
    timeout: 3
  resources:
    limits:
      cpu: "1"
      memory: "2048Mi"
    requests:
      cpu: "100m"
      memory: "512Mi"
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: loki
        - id: elastic
  env:
    - name: "OTEL_RESOURCE_ATTRIBUTES"
      value: "deployment.environment.name=p"
    - name: "PENSJON_REGLER_CLUSTER"
      value: "FSS"
  ingresses:
    - "https://pensjon-regler-beregn.dev.adeo.no"